/**
 * Compare the live database against `packages/db/src/schema.ts` and report
 * everything the schema declares but the database does not have.
 *
 * Why this exists: migrations 0010+ are hand-written SQL and are not in
 * drizzle's journal, so `db:migrate` will not apply them and `db:push` is
 * unsafe (it diffs the whole schema and does not know about the partitions,
 * the RLS policies or the enum ALTERs, so it proposes dropping them). In
 * practice that meant prod migrations were applied by hand — and on
 * 2026-07-31 an audit found SIX of them had never been applied: 0007, 0008,
 * 0009, 0011, 0012, 0013 and 0016. Seven detector rules had been firing into
 * a rejected INSERT the whole time.
 *
 * The expectations are derived from the drizzle schema objects themselves
 * rather than a hand-kept list, so a new column or index is covered the day
 * it is declared — a checklist that needs maintaining is the same discipline
 * problem that caused the drift.
 *
 * Usage: pnpm --filter @agentscope/scripts check-schema-drift
 *        (reads DATABASE_URL; exits 1 when anything is missing)
 */

import { createDb } from '@agentscope/db';
import * as schema from '@agentscope/db/schema';
import { is, sql } from 'drizzle-orm';
import { PgTable, getTableConfig, isPgEnum } from 'drizzle-orm/pg-core';

// ── Shapes ───────────────────────────────────────────────────────────────────

export interface ExpectedIndex {
  name: string;
  unique: boolean;
}

export interface ExpectedTable {
  name: string;
  columns: string[];
  indexes: ExpectedIndex[];
}

export interface ExpectedSchema {
  enums: { name: string; values: string[] }[];
  tables: ExpectedTable[];
}

export interface ActualSchema {
  /** enum type name → the labels it currently carries. */
  enums: Map<string, Set<string>>;
  /** table name → its column names. A missing key means the table is absent. */
  columns: Map<string, Set<string>>;
  /** index name → whether it is UNIQUE. */
  indexes: Map<string, { unique: boolean }>;
  /** relation name → `relrowsecurity`. Covers schema tables and partitions. */
  rls: Map<string, boolean>;
}

export type FindingKind =
  | 'missing-table'
  | 'missing-column'
  | 'missing-enum-value'
  | 'missing-index'
  | 'index-not-unique'
  | 'rls-disabled';

export interface Finding {
  kind: FindingKind;
  target: string;
  detail: string;
}

// ── Expectations, read off the drizzle schema ────────────────────────────────

/**
 * Derive expectations from the exported drizzle objects. Takes the schema
 * module as an argument so tests can pass a fixture instead of the real one.
 */
export function describeExpectedSchema(schemaModule: Record<string, unknown>): ExpectedSchema {
  const enums: ExpectedSchema['enums'] = [];
  const tables: ExpectedTable[] = [];

  for (const value of Object.values(schemaModule)) {
    if (isPgEnum(value)) {
      enums.push({ name: value.enumName, values: [...value.enumValues] });
      continue;
    }
    if (!is(value, PgTable)) continue;
    const config = getTableConfig(value);
    tables.push({
      name: config.name,
      columns: config.columns.map((column) => column.name),
      indexes: config.indexes
        // An index without an explicit name is generated by Postgres and
        // cannot be matched by name — skip rather than report a phantom.
        .filter((index) => typeof index.config.name === 'string')
        .map((index) => ({
          name: index.config.name as string,
          unique: index.config.unique === true,
        })),
    });
  }

  return { enums, tables };
}

// ── Comparison ───────────────────────────────────────────────────────────────

/**
 * Everything the schema declares and the database lacks.
 *
 * One-directional on purpose: extra columns and indexes in the database are
 * not reported. Postgres creates plenty on its own (primary keys, per-partition
 * index clones), and flagging them would bury the findings that matter under
 * noise nobody acts on.
 *
 * A missing table suppresses its own column and index findings — twelve lines
 * saying "column absent" adds nothing once you know the table is not there.
 */
export function compareSchema(expected: ExpectedSchema, actual: ActualSchema): Finding[] {
  const findings: Finding[] = [];

  for (const enumType of expected.enums) {
    const present = actual.enums.get(enumType.name);
    if (!present) {
      findings.push({
        kind: 'missing-enum-value',
        target: enumType.name,
        detail: `enum type is absent (expected ${enumType.values.length} values)`,
      });
      continue;
    }
    for (const value of enumType.values) {
      if (present.has(value)) continue;
      findings.push({
        kind: 'missing-enum-value',
        target: `${enumType.name}.${value}`,
        detail: `ALTER TYPE "public"."${enumType.name}" ADD VALUE IF NOT EXISTS '${value}';`,
      });
    }
  }

  for (const table of expected.tables) {
    const columns = actual.columns.get(table.name);
    if (!columns) {
      findings.push({
        kind: 'missing-table',
        target: table.name,
        detail: 'table does not exist — run the migration that creates it',
      });
      continue;
    }

    for (const column of table.columns) {
      if (columns.has(column)) continue;
      findings.push({
        kind: 'missing-column',
        target: `${table.name}.${column}`,
        detail: 'column declared in schema.ts but absent from the database',
      });
    }

    for (const index of table.indexes) {
      const live = actual.indexes.get(index.name);
      if (!live) {
        findings.push({
          kind: 'missing-index',
          target: index.name,
          detail: `index on "${table.name}" is absent`,
        });
        continue;
      }
      // The 0004 failure mode: the index exists but is not UNIQUE, so
      // ON CONFLICT has no constraint to match and every insert errors.
      if (index.unique && !live.unique) {
        findings.push({
          kind: 'index-not-unique',
          target: index.name,
          detail: `index on "${table.name}" exists but is NOT UNIQUE — ON CONFLICT will fail`,
        });
      }
    }
  }

  for (const [relation, enabled] of actual.rls) {
    if (enabled) continue;
    findings.push({
      kind: 'rls-disabled',
      target: relation,
      detail: `ALTER TABLE "${relation}" ENABLE ROW LEVEL SECURITY;`,
    });
  }

  return findings;
}

// ── Live read ────────────────────────────────────────────────────────────────

type Db = ReturnType<typeof createDb>;

async function readActualSchema(db: Db, expected: ExpectedSchema): Promise<ActualSchema> {
  const enumRows = (await db.execute(sql`
    SELECT t.typname AS type_name, e.enumlabel AS label
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    WHERE t.typnamespace = 'public'::regnamespace
  `)) as unknown as { type_name: string; label: string }[];

  const enums = new Map<string, Set<string>>();
  for (const row of enumRows) {
    const set = enums.get(row.type_name) ?? new Set<string>();
    set.add(row.label);
    enums.set(row.type_name, set);
  }

  const columnRows = (await db.execute(sql`
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
  `)) as unknown as { table_name: string; column_name: string }[];

  const columns = new Map<string, Set<string>>();
  for (const row of columnRows) {
    const set = columns.get(row.table_name) ?? new Set<string>();
    set.add(row.column_name);
    columns.set(row.table_name, set);
  }

  const indexRows = (await db.execute(sql`
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE schemaname = 'public'
  `)) as unknown as { indexname: string; indexdef: string }[];

  const indexes = new Map<string, { unique: boolean }>();
  for (const row of indexRows) {
    indexes.set(row.indexname, { unique: /CREATE\s+UNIQUE\s+INDEX/i.test(row.indexdef) });
  }

  // RLS is checked for the schema's own tables plus every partition of
  // agent_transactions. Postgres does not inherit RLS from a partitioned
  // parent, and PostgREST exposes each partition as its own endpoint — a
  // partition created without it is a readable copy of other users' rows.
  //
  // Every public table is fetched and the filtering happens in JS: passing the
  // expected names as a `= ANY($1)` parameter would compare `name` against
  // `text[]` and depend on an implicit cast, and the row count here is tiny.
  const rlsRows = (await db.execute(sql`
    SELECT c.relname, c.relrowsecurity
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
  `)) as unknown as { relname: string; relrowsecurity: boolean }[];

  const watched = new Set(expected.tables.map((t) => t.name));
  const rls = new Map<string, boolean>();
  for (const row of rlsRows) {
    if (!watched.has(row.relname) && !row.relname.startsWith('agent_transactions')) continue;
    rls.set(row.relname, row.relrowsecurity);
  }

  return { enums, columns, indexes, rls };
}

// ── CLI ──────────────────────────────────────────────────────────────────────

const KIND_LABELS: Record<FindingKind, string> = {
  'missing-table': 'MISSING TABLE',
  'missing-column': 'MISSING COLUMN',
  'missing-enum-value': 'MISSING ENUM VALUE',
  'missing-index': 'MISSING INDEX',
  'index-not-unique': 'INDEX NOT UNIQUE',
  'rls-disabled': 'RLS DISABLED',
};

export function formatReport(findings: Finding[]): string {
  if (findings.length === 0) return 'Schema matches packages/db/src/schema.ts — no drift.';
  const lines = [`Schema drift: ${findings.length} finding(s).`, ''];
  for (const finding of findings) {
    lines.push(`  [${KIND_LABELS[finding.kind]}] ${finding.target}`);
    lines.push(`      ${finding.detail}`);
  }
  lines.push('');
  lines.push('Apply the statements above against the target database, then re-run.');
  return lines.join('\n');
}

async function main(): Promise<void> {
  const connectionString = process.env['DATABASE_URL'];
  if (!connectionString) {
    console.error('DATABASE_URL is required');
    process.exit(2);
  }

  const db = createDb({ connectionString });
  const expected = describeExpectedSchema(schema as unknown as Record<string, unknown>);
  const actual = await readActualSchema(db, expected);
  const findings = compareSchema(expected, actual);

  console.info(formatReport(findings));
  // Exit code is the point: this is meant to be runnable as a pre-deploy gate,
  // where a human reading the output is not guaranteed.
  process.exit(findings.length === 0 ? 0 : 1);
}

// Only run when executed directly, so the pure functions stay importable.
if (process.argv[1]?.endsWith('check-schema-drift.ts')) {
  await main();
}
